modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory (24 is current forge version)
license="MIT License"
issueTrackerURL="https://github.com/aksource/MultiToolHolders/issues" #optional
displayURL="https://github.com/aksource/MultiToolHolders" #optional
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="ak" #optional
[[mods]] #mandatory
modId="multitoolholders" #mandatory
version="1.19-1.5.2.7" #mandatory
displayName="MultiToolHolders" #mandatory
updateJSONURL="https://raw.githubusercontent.com/aksource/MultiToolHolders/master/update.json" #optional
description='''
this add toolholders in Minecraft
'''